// themes.js — three visual directions for Kaplaaki expense form
window.THEMES = {
  "Classic Navy": {
    id: "Classic Navy",
    // Core palette
    primary: "#001F3F",
    accent: "#001F3F",
    accentLight: "#EEF4FF",
    accentBorder: "#C5D8F6",
    accentText: "#2C5282",
    // Page & cards
    pageBg: "#F5F5F0",
    cardBg: "#FFFFFF",
    cardBorder: "#E8E8E8",
    cardShadow: "none",
    // Text
    text: "#1A1A1A",
    textMuted: "#666666",
    textLight: "#999999",
    labelColor: "#555555",
    // Inputs
    inputBg: "#FAFAFA",
    inputBorder: "#DDDDDD",
    inputBorderWidth: "1.5px",
    // States
    errorBg: "#FEF2F2",
    errorBorder: "#FECACA",
    errorText: "#DC2626",
    successIcon: "#22C55E",
    // Accent blocks
    totalBg: "#EEF4FF",
    kmDisplayBg: "#EEF4FF",
    kmDisplayBorder: "#C5D8F6",
    kmDisplayText: "#2C5282",
    estiemInfoBg: "#EEF4FF",
    estiemInfoBorder: "#C5D8F6",
    estiemInfoText: "#2C5282",
    checklistBg: "#FAFAFA",
    // Header
    headerBg: "#001F3F",
    headerText: "#FFFFFF",
    headerStyle: "dark",
    // Typography
    bodyFont: "'Roboto Slab', serif",
    headingFont: "'Roboto Slab', serif",
    // Shape
    borderRadius: "8px",
    cardRadius: "10px",
    // Controls
    checkboxColor: "#22C55E",
    segmentActiveBg: "#001F3F",
    segmentActiveColor: "#FFFFFF",
    segmentInactiveBg: "#F0F0F0",
    segmentInactiveColor: "#666666",
    sectionTitleColor: "#001F3F",
    sectionTitleSize: "13px",
  },

  "Nordic Minimal": {
    id: "Nordic Minimal",
    primary: "#4F46E5",
    accent: "#4F46E5",
    accentLight: "#EEF2FF",
    accentBorder: "#C7D2FE",
    accentText: "#4338CA",
    pageBg: "#F8F9FC",
    cardBg: "#FFFFFF",
    cardBorder: "#E2E8F0",
    cardShadow: "0 1px 3px rgba(15,23,42,0.06), 0 1px 2px rgba(15,23,42,0.04)",
    text: "#0F172A",
    textMuted: "#64748B",
    textLight: "#94A3B8",
    labelColor: "#475569",
    inputBg: "#FFFFFF",
    inputBorder: "#CBD5E1",
    inputBorderWidth: "1px",
    errorBg: "#FFF1F2",
    errorBorder: "#FECDD3",
    errorText: "#E11D48",
    successIcon: "#16A34A",
    totalBg: "#EEF2FF",
    kmDisplayBg: "#EEF2FF",
    kmDisplayBorder: "#C7D2FE",
    kmDisplayText: "#4338CA",
    estiemInfoBg: "#EEF2FF",
    estiemInfoBorder: "#C7D2FE",
    estiemInfoText: "#4338CA",
    checklistBg: "#F8FAFC",
    headerBg: "#FFFFFF",
    headerText: "#0F172A",
    headerStyle: "light",
    bodyFont: "'DM Sans', sans-serif",
    headingFont: "'DM Sans', sans-serif",
    borderRadius: "6px",
    cardRadius: "12px",
    checkboxColor: "#4F46E5",
    segmentActiveBg: "#4F46E5",
    segmentActiveColor: "#FFFFFF",
    segmentInactiveBg: "#F1F5F9",
    segmentInactiveColor: "#64748B",
    sectionTitleColor: "#4F46E5",
    sectionTitleSize: "12px",
  },

  "Guild Heritage": {
    id: "Guild Heritage",
    primary: "#1B3A2D",
    accent: "#C5922E",
    accentLight: "#FDF6E3",
    accentBorder: "#E8D5A3",
    accentText: "#7A5C1A",
    pageBg: "#FAF7F0",
    cardBg: "#FEFDF9",
    cardBorder: "#E5DFD5",
    cardShadow: "0 1px 4px rgba(27,58,45,0.07)",
    text: "#1A1612",
    textMuted: "#6B5E4E",
    textLight: "#A89880",
    labelColor: "#4A3F32",
    inputBg: "#FDFCF9",
    inputBorder: "#D8CFBF",
    inputBorderWidth: "1px",
    errorBg: "#FEF3F2",
    errorBorder: "#F5C6C0",
    errorText: "#C0392B",
    successIcon: "#27AE60",
    totalBg: "#FDF6E3",
    kmDisplayBg: "#FDF6E3",
    kmDisplayBorder: "#E8D5A3",
    kmDisplayText: "#7A5C1A",
    estiemInfoBg: "#FDF6E3",
    estiemInfoBorder: "#E8D5A3",
    estiemInfoText: "#7A5C1A",
    checklistBg: "#FAF7F0",
    headerBg: "#1B3A2D",
    headerText: "#FAF7F0",
    headerStyle: "dark",
    bodyFont: "'Source Sans 3', sans-serif",
    headingFont: "'Playfair Display', serif",
    borderRadius: "4px",
    cardRadius: "8px",
    checkboxColor: "#C5922E",
    segmentActiveBg: "#1B3A2D",
    segmentActiveColor: "#FAF7F0",
    segmentInactiveBg: "#F0EBE0",
    segmentInactiveColor: "#6B5E4E",
    sectionTitleColor: "#1B3A2D",
    sectionTitleSize: "13px",
  },
};
